<p data-bbox="18,28,356,143"># 人民日报</p>
<p data-bbox="105,154,288,172"># RENMIN RIBAO</p>
<p data-bbox="91,192,300,203">人民网网：http://www.people.com.cn</p>
<p data-bbox="16,227,177,260">为推动行业协会商会深化改革，促进行业协会商会规范健康发展，经党中央、国务院同意，现提出如下意见。</p>
<p data-bbox="56,272,134,286"># 一、总体要求</p>
<p data-bbox="16,294,177,458">坚持以习近平新时代中国特色社会主义思想为指导，深入贯彻党的二十大和二十届历次全会精神，坚持和加强党的全面领导，坚持以人民为中心，坚持稳中求进工作总基调，完整准确全面贯彻新发展理念，强化创新驱动，聚焦重组创新发展又注重严格监督管理，健全与高水平社会主义市场经济体制相适应的行业协会商会管理制度与运行机制，完善政府监管、社会监督、自律自治相结合的社会治理体系，优化行业协会商会结构布局和运行环境，推动行业协会商会规范运行、专业化、规范化的要求转型发展，充分发挥行业协会商会在服务经济社会发展中的积极作用。</p>
<p data-bbox="16,468,175,484"># 二、坚持和加强党的全面领导</p>
<p data-bbox="16,493,176,602">（一）理顺建会工作管理体制。加快构建建会统合、上下联动、有效协同的党建工作格局，建立健全“管业务也要管党建”工作机制，落实全部门齐抓共管工作责任。进一步理顺行业协会商会党组织隶属关系，健全领导全覆盖、顺畅运行的党组织体系。有条件主管单位的行业协会商会按党建工作，由业务主管单位党组织领导和管理，接受受主管单位部门的工作领导。</p>
<p data-bbox="16,602,176,717">（二）增强党组织政治功能和组织功能。提高党的组织和党的工作覆盖率，健全党领导下的行业社会组织管理制度，完善党建需求提级提升机制，推进党业融合发展规范运行，全面夯实建会工作基础。行业协会商会党组织要严格按照党章和有关党的法规制度履职，贯彻落实党中央决策部署，强化引领发展的政治责任，把非公有制经济领域的从业人员凝聚服务好，严格掌握意识形态工作责任制，有效防范化解涉意识形态领域风险。</p>
<p data-bbox="196,231,287,712"># 推动行业协会商会深化改革的意见 中共中央办公厅 国务院办公厅关于</p>
<p data-bbox="336,228,494,355">（三）加强换届规范和负责人队伍建设。依规依法依章程严格规范换届，推动行业协会商会党组织有效参与重大事项决策等重大事项制度，建立健全理事会按程序和负责人到会督促进换届机制，规范非公换党换届，加强组织乱象整治，加大对换届违规行为的打击和惩戒力度。党委社会工作部门要提出党委标准，强化政治把关，做好负责人人选审核工作。建立健全行业协会商会负责人提名、审核、公示、监督、提出等制度，推动党员管理层人员与党组织班子或实行“双向进入、交叉任职”。建立健全非公有制企业入党积极分子任用制度，严格规范负责人名册资料设置。加强对负责人的监督管理，对不符合条件以及不符合、不称职等不适宜担任负责人人员及时调整。</p>
<p data-bbox="335,422,494,522">（四）持续加大直接扶持力度。行业协会商会党组织要切实健全全面从严治党主体责任，内设纪检监察组织要履行监督责任，结合实际健全组织工作机制。加强纪检监察工作规范化法治化正规化建设，建立和完善题中要处理量度，严肃查处违反中央八项规定精神等违规违纪行为。完善行业协会商会反腐败制度体系，深化整治不正之风和腐败问题，一体推进不敢腐、不能腐、不想腐。</p>
<p data-bbox="336,531,492,558"># 三、完善行业协会商会管理制度与运行机制</p>
<p data-bbox="335,572,494,672">（五）巩固拓展政治效果。建立健全党委统一领导、党委社会工作部门统筹协调、登记管理机关、行业管理部门、业务主管单位、相关职能部门各司其职、协同配合、综合监管的管理机制。对有业务主管单位的行业协会商会，要要求逐步推动机制合并、职能分离、财尽独立、人事自主，加强日常指导和管理监督，实现依法自主规范运行和健康有序发展。</p>
<p data-bbox="335,675,492,717">（六）持续深化登记制度改革。研究制定行业协会商会设置登记管理办法，登记信息公开管理办法，在设立登记时同步列明行业管理部门。</p>
<p data-bbox="20,745,485,784"># 赵乐际同新西兰议长布朗利会谈</p>
<p data-bbox="16,796,166,828">新华社北京4月13日电 全国人大常委会委员长赵乐际13日在北京人民大会堂同新西兰总检察长阿伦·利文斯顿会谈。</p>
<p data-bbox="16,828,166,892">赵乐际表示，当前中新关系保持良好发展势头，各领域务实合作不断涌现，中方向新西兰一方一道，落实好近来中新双方领导人的重要共识，加强战略沟通，深化务实合作，推动中新建全面战略伙伴关系的进展。</p>
<p data-bbox="16,894,166,984">赵乐际指出，相互尊重、彼此包容、聚焦合作、共同发展，是中国外交的立身之基和处世之经。双方要深化互信与互信，坚守交流交心，发扬“争先”精神，以合作应对挑战共商，尊重彼此核心利益和重大关切。中方赞赏新方多边采取坚持一个中国政策。中方愿同新西兰开展发廊与合作，深化农业、机电等传统</p>
<p data-bbox="179,796,327,892">领域合作，探索加强数字经济、绿色转型、人工智能等新兴领域合作，打造更多契合两国发展需求的合作增长点。双方要增进互访与交流，深化两国民众特别是青年一代友好交往，促进双方交流。加强在联合体、世贸组织等多边框架下的沟通协调，共担推进全球有序的世界级公共、普惠包容的全球经济。</p>
<p data-bbox="179,894,328,982">赵乐际强调，中国全国人大愿同新西兰议会一道，保持多渠道、多领域友好交往的良好势头，立足立法机构职能和特色，开展治理理论经验交流，为两国关系合作提供法律保障。赵乐际介绍了“十五五”规划期要和生态文明有了新进展，表示欢迎更多西方企业赴展和深耕中国市场，中方愿同新方开展</p>
<p data-bbox="342,796,491,828">生态循环立法、绿色低碳发展、应对气候变化方面的经验交流和务实合作。</p>
<p data-bbox="342,829,492,892">布朗利表示，新西兰高度重视对华合作，在相互信任、增进交流的基础上，中新关系不断走深走实。新西兰愿在一个中国政策、两国都致力于让人民生活变得更好基础上，深化共识着眼到中国发展得好的大趋势。两国在经贸、新能源、教育、青年、气候变化等领域合作成果丰硕，人文在双边关系中发挥着重要作用，新议会代表团成员来自新名委员，都支持进一步发展对华关系。新议会在加强同中国全国人大友好交往上，在立法等领域深化立法，加强相互了解和人民友谊，为促进中新各实合作出积极贡献。</p>
<p data-bbox="360,972,428,982">张庆伟参加会谈。</p>
<p data-bbox="515,18,682,35"># 读者看点·共同关注</p>
<p data-bbox="515,50,986,82"># 国家安全“大事”，跟普通人有什么关系？</p>
<p data-bbox="709,94,793,106">本报记者 齐工武</p>
<p data-bbox="402,118,661,146">最近，在许多场所看到4月15日“全民国家安全教育日”的海报，国家安全的“大事”，跟普通人有什么关系？</p>
<p data-bbox="589,153,653,163">一人民网网友</p>
<p data-bbox="515,172,662,216">一提到国家安全，很多人往往会想到军警特卫、防火防汛、反间谍等，觉得这些事是专门机关的职责，离自己很远。</p>
<p data-bbox="515,219,662,264">实际上，国家安全的内涵和外延已大大拓展。随着技术变革和生产生活方式的变化，安全需求提高，生态、网络、人工智能、数据等方面的安全已经融入人们生活的方方面面。</p>
<p data-bbox="515,266,662,355">举几个例子：随着点击的陌生网络链接，可能成为境外黑客攻击的人口；私自从境外带回的水果蔬菜、动物标本，可能威胁国家生态安全；手机随意拍摄的敏感场景，可能成为泄露国家秘密的“定时炸弹”；社交网络上的“高新翻译”语感，可能泄露军事调动的暗语……</p>
<p data-bbox="515,357,661,392">这些并非耸人听闻，而是有往年的警示案例，有人为此栽跟头、铸大错悔不晚矣。</p>
<p data-bbox="515,394,662,414">进一步说，一碗热腾腾的米饭，来自国家安全粮食的支持；深度安全深</p>
<p data-bbox="676,118,822,146">出门吃夜宵，背后是社会安全的有力保障……</p>
<p data-bbox="676,141,824,172">国家安全的“大事”，和普通人紧密相连，它就在我们身边，就在日常生活的每一天。</p>
<p data-bbox="676,174,824,242">2014年4月15日，习近平总书记创造性提出总体国家安全观，即统筹发展和安全，国家安全和社会稳定、国内和国际、顶上和基层、传统安全和非传统安全，实现国家安全覆盖。</p>
<p data-bbox="676,243,824,321">2015年7月，国家安全法颁布实施，有力保障了总体国家安全观贯彻落实。这部法律规定，每年4月15日为“全民国家安全教育日”。设立普及日的意义，不仅在于普及知识，更在于推动行动。</p>
<p data-bbox="676,323,825,414">维护国家安全，谁都不能触手旁观、置身事外。从“路人甲”到“守门员”，普通人可以成为、也应当成为国家安全的坚实后盾；多一些警惕、更能用人工智能为强化风险意识、不断提高预警与救援能力，发现问题及时为报道少一点伤害一不随意拍摄、传播敏感场景信息，不信谣、不传谣……</p>
<p data-bbox="676,414,824,419">这些年，随着国家安全宣传课程的</p>
<p data-bbox="676,419,824,419">深入开展，越来越多人认识到，每个人</p>
<p data-bbox="831,118,985,153">既是国家安全的获得感者、受益者，也是参与者、共建者。</p>
<p data-bbox="831,153,985,242">在总体国家安全观的指引下，我们有效化解了一系列重大风险挑战，国家安全得到全面加强，成功捍卫“两个确立”新赛果。我国群众安全感由2012年的87.53%上升至2025年的98.23%，国际社会普遍认为中国是世界上最安全的国家之一；粮食自产量连续两年站稳1.4万亿斤台阶，“中国饭碗”端得更加安全；2025年全国PM2.5平均浓度为28.0微克/立方米，生态环境质量持续改善。</p>
<p data-bbox="831,243,985,321">比如疫情防控，我们不是生活在和平的世界，而是生活在和平的国家。“方向事关前途命运，道路决定命运，百姓离不开方向；向内，身处的祖国稳如泰山，安全如空气一般伴随着我们，走向式现代化行稳致远提供坚实支撑。”</p>
<p data-bbox="831,323,985,414">来之不易的国家安全，需要你我的共同守护。每一个普通人以身做故、从小事做起，把维护国家安全融入日常，国家安全的铜墙铁壁才能更不可破，国家安全的幸福生活才能长久久。</p>
<p data-bbox="522,442,976,472"># 李强同阿联酋阿布扎比王储哈立德会谈</p>
<div class="image" data-bbox="515,491,803,667"><img data-bbox="515,491,803,667"/></div>
<p data-bbox="516,675,785,695">4月13日下午，国务院总理李强在北京人民大会堂同来华访问的阿联酋阿布扎比王储哈立德举行会谈。新华社记者 黄敬文摄</p>
<p data-bbox="800,491,985,627">氢能、智能网联汽车、动力电池等领域合作，促进两国绿色转型。双方要打造更多贸易增长点，既扩大规模，也优化结构。中方愿进口阿方更多优质产品，欢迎阿方积极参与共享大市场、出口中国市场活动，用好中国进博会、服贸会等平台加大产品推介。中阿在创新成果领域的合作前景广阔，中方欢迎阿方加大在人工智能、数字经济、先进制造、生命科学等领域的中非投资，支持两国高校、科研机构和企业加强联合研究和人才培养，共同培育大新兴和未来产业。双方还可以加强互联互通、金融等领域合作，不断促进贸易和投资便利化。</p>
<p data-bbox="800,628,985,682">李强表示，伊朗战事缓和以来，中方一直同有关各方密切沟通，积极致力于促进以治上、中方愿进一步发挥建设性作用，为恢复海湾地区和平安宁作出贡献。希望阿方继续采取有力措施，保障在阿中国公民、机构和财产安全。</p>
<p data-bbox="800,684,985,747">哈立德表示，中国是阿联酋重要的全面战略伙伴和优先领域的长期关键合作伙伴，两国深化经贸、基建、通信、航天、能源、科技创新、文化等領域合作成效，更好应对全球优先地位，愿同中方进一步密切高层往来，拓展贸易、投资、能源、科技创新、数字、文化等领域交流合作，更好服务两国发展和两国人民利益。当前中东地区形势多变，中方始终致力于通过和平手段和平解决地缘政治议题和相关，同对方及地区国家对此高度赞赏。阿方期待中方继续为促进地区和平安全发挥重要作用，愿采取一切必要措施维护在阿中国公民安全。</p>
<p data-bbox="757,748,985,828">会见后，李强和哈立德共同见证签署农业、科技、投资、中医药等领域多边合作文件。吴秋峰参加上述活动。</p>
<p data-bbox="515,867,985,932"># 丁薛祥将访问土库曼斯坦、作为习近平主席特别代表出席复兴气田四期项目开工仪式、举行中土合作委员会第七次会议</p>
<p data-bbox="513,947,985,982">本报北京4月13日电 外交部发言人4月13日宣布：土库曼斯坦正方面邀请，中共中央政治局常委、国务院副总理丁薛祥将于4月15日至17日访问土库曼斯坦，作为习近平主席特别代表出席复兴气田四期项目开工仪式。 访土期间，丁薛祥副总理作为中土合作委员会中方主席，将同土方共同主持召开委员会第七次会议。</p>
