<p data-bbox="31,14,974,58">秋之令，果以成实，欲得刚金而修剪。霜降後不宜水盛，水盛则木漂。寒露节又喜火炎，火炎则木实。木多有多材之美，土厚无自任之能。</p>
<p data-bbox="31,62,974,107">冬月之木，虚屈在地，欲土多而培养。恶水盛而忘形。金总多不能克伐。火重见温暖有功。归根复命之时。木病安能辅助，须忌死绝之地，只宜生旺之方。</p>
<p data-bbox="33,136,206,157"># 三春甲木总论</p>
<p data-bbox="31,162,977,283">春月之木，渐有生长之象。初春犹有余寒，当以火温暖，则有舒畅之美，水多变克，有损精神。重见生旺，必用庚金斲凿，可成栋梁。春末阳壮水渴，藉水资源扶，则花繁叶茂。初春无火，增之以水，则阴浓气弱，根振枝枯，不能华秀。春末失水，增之以火，则阳气太盛，燥渴相加，枝枯叶乾，亦不华秀。是以水火二物，要得时相济为美。</p>
<p data-bbox="33,311,144,332"># 三春甲木</p>
<p data-bbox="31,336,974,381">正月甲木，初春尚有余寒，得丙癸逢，富贵双全。癸藏丙透，名寒木向阳，主大富贵。倘风水不及，亦不失儒林俊秀。如无丙癸，平常人也。</p>
<p data-bbox="31,385,974,527">正二月甲木，素无取从才从杀从化之理。或一派庚辛，主一生劳苦，克子刑妻，再支会金局，非贫即夭。如无丙丁，一派壬癸，又无戊己制之，名水泛木浮，死无棺椁。如一派戊己，支会金属，为财身多弱，富屋贫人，终生劳苦，妻晚子迟。或无庚金，有丁透，亦属文星，为木火通明之象，又名伤官生财格，主聪明雅秀。一见癸水伤丁，但作厚道迂儒。或柱中多癸，滋助木神，伤灭丁火，其人奸雄枭险，曹操之徒，言清行浊，笑里藏刀。</p>
<p data-bbox="31,530,974,576">若庚申、戊寅、甲寅、丙寅。一行金水运，发进士。或甲午日庚午时，此人必贵。但要好运相催，不宜制了庚丁。</p>
<p data-bbox="31,579,974,694">或支成金局，多透庚辛，此又不吉，号曰木被金伤，若无丙丁破金，必主残疾。或支成火局，泄露太过，定主愚懦，常有啾唧灾病缠身，终有暗疾。支成木局，得庚为贵，无庚必凶，若非僧道，男主鳏孤，女主寡独。支成水局，戊透为贵，如无戊制，不但贫贱，且死无棺木。故书曰：甲木若无根，全赖申子辰，干得才杀透，平步上青云。</p>
<p data-bbox="31,700,865,723">凡三春甲木，用庚者，土为妻，金为子。用丁者，木为妻，火为子。</p>
<p data-bbox="31,722,807,745">总之正二月甲木，有庚戊者上命。如有丁透，大富大贵之命也。</p>
<p data-bbox="31,748,977,843">二月甲木，庚金得所，名阳刃驾杀，可云小贵，并途显达，或主武职，但要财资之。柱中逢才，英雄独压万人。若见癸水，困了才杀，主为光棍，重刀必定遭凶。性情凶暴。书曰：木旺宜火之光辉，秋闻可试。木向春生，处世安然有寿。日主无依，却喜运行才地。</p>
<p data-bbox="31,847,974,917">三月甲木，木气相碍。先取庚金，次用壬水。庚壬两透，一榜堪图。但要运用相生，风水阴德，方许富贵。</p>
<p data-bbox="31,900,694,918">或见一二庚金，独取壬水。壬透清秀之人，才学必富。</p>
<p data-bbox="31,922,974,966">或天干透出二丙，庚藏支下，此纯斧无钢，富贵难求。若有壬癸破火，堪作秀才。</p>
<p data-bbox="31,971,974,993">或柱中全无一水，戊己透干，支成土局，又作奔命从才，因人而致富贵，妻子</p>
