

赶紧把胖子都围上围裙。再看他皮肤下面还有很多特别小的小蚂蚁，胖子用手和烟都没用，直接拿出菜刀，片开一点皮肤，再用打火机把小蚂蚁烫出来。




正搞着，就听到外面好像有车的声音，我也没多想。很快，村支书就带着一群陌生人抖着肩进来了，还没进门就喊道：“吴老板，麻烦你加个班，我们镇上领导的朋友从青海慕名而来。说你们这儿的菜特别好吃，在网上很红，大概十几个人，你上点你的拿手菜。”




说完他推开门，就看到我提着开水桶，胖子拿着菜刀围在桌子旁。两个人都穿着围裙，桌子上是一个两百多斤，特别白但不省人事的全裸大汉，身上还都是血。




一行十几个人都愣住了，村支书原本想说句俏皮话，结果一看这情况就秃噜嘴了，结巴道：“这么一分——分——分尸呢？” 随即，村支书几乎咬到舌头，求救似的看着我。




胖子就笑，他刚才也没意识到，随口问道：“来一块吗？”




我咳嗽了一声：“这是我的乙方你信吗？”




跟来的游客全部都目瞪口呆，大家僵持着。我深吸了一口气，刚想好好解释，闪油瓶单肩扛着赤裸的王盟就挤开人群进来了，放到另外一张桌子上。


